version: '3'
services:
  irrigatop:
    container_name: irrigatop
    restart: always
    build:
      context: .
    ports:
      - "59688:5000"
      - 5678:5678
    volumes:
      - ./data:/app/instance
      - ./:/app #Debug only
    environment:
      - FLASK_DEBUG=1
      - PYTHONUNBUFFERED=1
      - MQTT_BROKER=35.184.104.130
      - MQTT_TOPIC=irrigation
      - MQTT_TOPIC_STATUS=irrigation/status
      - MQTT_PORT=59687
      - MQTT_USERNAME=irrigatop
      - MQTT_PASSWORD=irrigatop
      - BASIC_AUTH_USERNAME=irrigador
      - BASIC_AUTH_PASSWORD=molhadinho123@#
